name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hugo 源码所在的分支
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # 使用了 Git 子模块
          fetch-depth: 0     # 确保获取完整的 Git 历史记录

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # 如果是 Hugo Extended 版本

      - name: Build
        run: hugo --minify  # 构建 Hugo 站点

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}  # 确保 GITHUB_TOKEN 是在你的 GitHub 仓库的 Secrets 中设置的
          publish_branch: gh-pages  # 指定推送到哪个分支
          publish_dir: ./public  # Hugo 默认的构建输出目录
